language: python
python:
- "3.6"
- "3.7"
- "3.8"

install:
  - python --version
  - pip --version
  - pip install --upgrade setuptools
  
  - pwd
  - git clone --depth=50 --branch=master https://github.com/bjornaa/ladim.git ../ladim
  - pip install ../ladim
  
  - pip install .
  - pip list

script:
  - pytest -Wignore --pyargs ladim_plugins
