language: python
python:
- "3.6"
- "3.7"
- "3.8"

install:
  - python --version
  - pip --version
  - pip install --upgrade setuptools numpy
  - pip install git+https://github.com/bjornaa/ladim.git
  - pip install .
  - pip list

script:
  - pytest -Wignore --pyargs ladim_plugins
